import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import type { Tables } from "@/types/supabase";
import AppHeader from "@/components/AppHeader";

type Company = Pick<Tables<'companies'>, 'id' | 'company_name' | 'industry' | 'description' | 'target_customers' | 'key_differentiators'>;

interface ContentTemplate {
  id: string;
  type: string;
  title: string;
  description: string;
  icon: string;
  aiOptimized: boolean;
}

const QuickTestContent = () => {
  const { user } = useAuth();
  const [company, setCompany] = useState<Company | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedContentType, setSelectedContentType] = useState("blog");
  const [contentTitle, setContentTitle] = useState("");
  const [contentTopic, setContentTopic] = useState("");
  const [generatedContent, setGeneratedContent] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState('generate');

  const contentTemplates: ContentTemplate[] = [
    {
      id: "blog",
      type: "Blog Post",
      title: "Thought Leadership Blog",
      description: "Generate AI-optimized blog posts that position you as an industry expert",
      icon: "✍️",
      aiOptimized: true
    },
    {
      id: "faq",
      type: "FAQ Page",
      title: "Comprehensive FAQ",
      description: "Create detailed FAQ pages that answer common customer questions",
      icon: "❓",
      aiOptimized: true
    },
    {
      id: "case-study",
      type: "Case Study",
      title: "Customer Success Story",
      description: "Showcase customer wins and demonstrate your value proposition",
      icon: "📈",
      aiOptimized: true
    },
    {
      id: "press-release",
      type: "Press Release",
      title: "Company Announcement",
      description: "Professional press releases for company news and achievements",
      icon: "📰",
      aiOptimized: false
    }
  ];

  const loadCompanyData = useCallback(async () => {
    try {
      const { data: companies, error } = await supabase
        .from('companies')
        .select('*')
        .eq('user_id', user?.id);

      if (error) {
        console.error('Error loading company:', error);
        return;
      }

      const company = companies && companies.length > 0 ? companies[0] : null;
      if (company) {
        setCompany(company);
      }
    } catch (error) {
      console.error('Error loading data:', error);
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    if (user) {
      loadCompanyData();
    }
  }, [user, loadCompanyData]);

  const generateContent = async () => {
    if (!contentTopic.trim() || !company) return;

    try {
      setIsGenerating(true);
      
      // Simulate content generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const mockContent = `# ${contentTitle || `${contentTemplates.find(t => t.id === selectedContentType)?.type}: ${contentTopic}`}

## Introduction
This ${contentTemplates.find(t => t.id === selectedContentType)?.type.toLowerCase()} focuses on ${contentTopic} in the ${company.industry} industry.

## Key Points
- Industry expertise in ${company.industry}
- Target audience: ${company.target_customers}
- Key differentiators: ${company.key_differentiators}

## Content Body
${company.description}

This content has been optimized for AI training data inclusion and improved visibility in AI-generated responses.

## Conclusion
${company.company_name} is positioned as a leader in ${company.industry} with focus on ${contentTopic}.

---
*Generated by AI Spotlight Pro Content Assistant*`;
      
      setGeneratedContent(mockContent);
      alert('Your AI-optimized content is ready for review and publishing.');
    } catch (error) {
      console.error('Error generating content:', error);
      alert('Failed to generate content. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  if (loading) {
    return (
      <div style={{ minHeight: '100vh', background: '#111', color: '#fff' }}>
        <AppHeader />
        <div style={{ textAlign: 'center', paddingTop: '100px' }}>
          <div style={{ fontSize: '18px' }}>Loading Content Assistant...</div>
        </div>
      </div>
    );
  }

  if (!company) {
    return (
      <div style={{ minHeight: '100vh', background: '#111', color: '#fff' }}>
        <AppHeader />
        <div style={{ textAlign: 'center', paddingTop: '100px' }}>
          <div style={{ fontSize: '24px', marginBottom: '20px' }}>⚠️ No Company Profile Found</div>
          <div style={{ fontSize: '16px', marginBottom: '30px', color: '#888' }}>
            You need to set up your company profile first to access AI content generation.
          </div>
          <button
            onClick={() => window.location.href = '/geo'}
            style={{
              background: '#007bff',
              color: 'white',
              padding: '12px 24px',
              border: 'none',
              borderRadius: '6px',
              fontSize: '16px',
              cursor: 'pointer'
            }}
          >
            Set Up Company Profile
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: '100vh', background: '#111', color: '#fff' }}>
      <AppHeader />
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '20px' }}>
        {/* Header */}
        <div style={{
          borderBottom: '1px solid #333',
          paddingBottom: '20px',
          marginBottom: '30px'
        }}>
          <h1 style={{ margin: '0 0 10px 0', fontSize: '32px' }}>Content Assistant</h1>
          <p style={{ margin: 0, color: '#888', fontSize: '16px' }}>
            Generate AI-optimized content that improves your visibility in AI responses
          </p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '30px' }}>
          {/* Content Templates */}
          <div>
            <div style={{
              background: '#222',
              padding: '20px',
              borderRadius: '8px',
              border: '1px solid #333'
            }}>
              <div style={{ marginBottom: '15px' }}>
                <h2 style={{ margin: '0 0 5px 0', fontSize: '18px' }}>✨ Content Templates</h2>
                <p style={{ margin: 0, color: '#888', fontSize: '14px' }}>
                  Choose a content type optimized for AI visibility
                </p>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {contentTemplates.map((template) => (
                  <div
                    key={template.id}
                    style={{
                      padding: '12px',
                      borderRadius: '6px',
                      border: selectedContentType === template.id ? '2px solid #007bff' : '1px solid #333',
                      background: selectedContentType === template.id ? '#1a365d' : '#111',
                      cursor: 'pointer'
                    }}
                    onClick={() => setSelectedContentType(template.id)}
                  >
                    <div style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
                      <span style={{ fontSize: '20px' }}>{template.icon}</span>
                      <div style={{ flex: 1 }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                          <h4 style={{ margin: 0, fontSize: '14px', fontWeight: '600' }}>{template.title}</h4>
                          {template.aiOptimized && (
                            <span style={{
                              background: '#28a745',
                              color: 'white',
                              padding: '2px 6px',
                              borderRadius: '4px',
                              fontSize: '10px',
                              fontWeight: 'bold'
                            }}>
                              AI Optimized
                            </span>
                          )}
                        </div>
                        <p style={{ margin: 0, fontSize: '12px', color: '#888' }}>{template.description}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Content Generation */}
          <div>
            {/* Tab Navigation */}
            <div style={{ marginBottom: '20px' }}>
              <div style={{ display: 'flex', gap: '10px' }}>
                <button
                  onClick={() => setActiveTab('generate')}
                  style={{
                    background: activeTab === 'generate' ? '#007bff' : '#333',
                    color: '#fff',
                    padding: '12px 20px',
                    border: 'none',
                    borderRadius: '6px',
                    cursor: 'pointer'
                  }}
                >
                  Generate Content
                </button>
                <button
                  onClick={() => setActiveTab('library')}
                  style={{
                    background: activeTab === 'library' ? '#007bff' : '#333',
                    color: '#fff',
                    padding: '12px 20px',
                    border: 'none',
                    borderRadius: '6px',
                    cursor: 'pointer'
                  }}
                >
                  Content Library
                </button>
              </div>
            </div>

            {activeTab === 'generate' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                {/* Content Form */}
                <div style={{
                  background: '#222',
                  padding: '20px',
                  borderRadius: '8px',
                  border: '1px solid #333'
                }}>
                  <div style={{ marginBottom: '15px' }}>
                    <h2 style={{ margin: '0 0 5px 0', fontSize: '18px' }}>AI Content Generator</h2>
                    <p style={{ margin: 0, color: '#888', fontSize: '14px' }}>
                      Generate content optimized for AI training data inclusion
                    </p>
                  </div>

                  <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                      <div>
                        <label style={{ display: 'block', marginBottom: '5px', fontSize: '14px', fontWeight: '500' }}>
                          Content Title (Optional)
                        </label>
                        <input
                          type="text"
                          value={contentTitle}
                          onChange={(e) => setContentTitle(e.target.value)}
                          placeholder="Enter a custom title"
                          style={{
                            width: '100%',
                            padding: '10px',
                            background: '#333',
                            border: '1px solid #555',
                            borderRadius: '6px',
                            color: '#fff'
                          }}
                        />
                      </div>
                      <div>
                        <label style={{ display: 'block', marginBottom: '5px', fontSize: '14px', fontWeight: '500' }}>
                          Content Type
                        </label>
                        <select 
                          value={selectedContentType} 
                          onChange={(e) => setSelectedContentType(e.target.value)}
                          style={{
                            width: '100%',
                            padding: '10px',
                            background: '#333',
                            border: '1px solid #555',
                            borderRadius: '6px',
                            color: '#fff'
                          }}
                        >
                          {contentTemplates.map((template) => (
                            <option key={template.id} value={template.id}>
                              {template.type}
                            </option>
                          ))}
                        </select>
                      </div>
                    </div>

                    <div>
                      <label style={{ display: 'block', marginBottom: '5px', fontSize: '14px', fontWeight: '500' }}>
                        Topic/Subject
                      </label>
                      <input
                        type="text"
                        value={contentTopic}
                        onChange={(e) => setContentTopic(e.target.value)}
                        placeholder="What topic should the content focus on?"
                        style={{
                          width: '100%',
                          padding: '10px',
                          background: '#333',
                          border: '1px solid #555',
                          borderRadius: '6px',
                          color: '#fff'
                        }}
                      />
                    </div>

                    <button 
                      onClick={generateContent}
                      disabled={!contentTopic.trim() || isGenerating}
                      style={{
                        background: isGenerating ? '#666' : '#28a745',
                        color: 'white',
                        padding: '15px',
                        border: 'none',
                        borderRadius: '6px',
                        cursor: isGenerating ? 'not-allowed' : 'pointer',
                        fontSize: '16px',
                        fontWeight: '600'
                      }}
                    >
                      {isGenerating ? '⏳ Generating Content...' : '⚡ Generate AI-Optimized Content'}
                    </button>
                  </div>
                </div>

                {/* Generated Content */}
                {generatedContent && (
                  <div style={{
                    background: '#222',
                    padding: '20px',
                    borderRadius: '8px',
                    border: '1px solid #333'
                  }}>
                    <div style={{ marginBottom: '15px' }}>
                      <h2 style={{ margin: 0, fontSize: '18px' }}>Generated Content</h2>
                      <p style={{ margin: '5px 0 0 0', color: '#888', fontSize: '14px' }}>
                        Content optimized for AI training data inclusion and improved visibility
                      </p>
                    </div>

                    <textarea
                      value={generatedContent}
                      onChange={(e) => setGeneratedContent(e.target.value)}
                      style={{
                        width: '100%',
                        minHeight: '300px',
                        padding: '15px',
                        background: '#333',
                        border: '1px solid #555',
                        borderRadius: '6px',
                        color: '#fff',
                        fontSize: '14px',
                        fontFamily: 'monospace',
                        resize: 'vertical'
                      }}
                    />

                    <div style={{ display: 'flex', gap: '10px', marginTop: '15px' }}>
                      <button
                        onClick={() => {
                          navigator.clipboard.writeText(generatedContent).then(() => {
                            alert('Content copied to clipboard!');
                          });
                        }}
                        style={{
                          background: '#6c757d',
                          color: 'white',
                          padding: '10px 15px',
                          border: 'none',
                          borderRadius: '6px',
                          cursor: 'pointer',
                          fontSize: '14px'
                        }}
                      >
                        📋 Copy to Clipboard
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}

            {activeTab === 'library' && (
              <div style={{
                background: '#222',
                padding: '20px',
                borderRadius: '8px',
                border: '1px solid #333'
              }}>
                <div style={{ marginBottom: '15px' }}>
                  <h2 style={{ margin: '0 0 5px 0', fontSize: '18px' }}>Content Library</h2>
                  <p style={{ margin: 0, color: '#888', fontSize: '14px' }}>
                    Your previously generated and saved content pieces
                  </p>
                </div>

                <div style={{ textAlign: 'center', padding: '60px 20px', color: '#888' }}>
                  <div style={{ fontSize: '48px', marginBottom: '15px' }}>📄</div>
                  <p style={{ margin: '0 0 5px 0' }}>No saved content yet</p>
                  <p style={{ margin: 0, fontSize: '12px' }}>Generated content will appear here</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Navigation */}
        <div style={{
          marginTop: '40px',
          padding: '20px 0',
          borderTop: '1px solid #333',
          display: 'flex',
          gap: '15px',
          flexWrap: 'wrap'
        }}>
          <button
            onClick={() => window.location.href = '/dashboard'}
            style={{
              background: '#6c757d',
              color: 'white',
              padding: '12px 20px',
              border: 'none',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '14px'
            }}
          >
            🏠 Dashboard
          </button>
          <button
            onClick={() => window.location.href = '/geo'}
            style={{
              background: '#007bff',
              color: 'white',
              padding: '12px 20px',
              border: 'none',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '14px'
            }}
          >
            🎯 My GEO
          </button>
          <button
            onClick={() => window.location.href = '/competitors'}
            style={{
              background: '#28a745',
              color: 'white',
              padding: '12px 20px',
              border: 'none',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '14px'
            }}
          >
            🏆 Competitor Analysis
          </button>
        </div>
      </div>
    </div>
  );
};

export default QuickTestContent;